services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file: .env

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8081:8080
  app:
    build:
      context: .
      args:
        DATABASE_PROVIDER: postgresql
        DATABASE_URL: postgresql://admin:example@127.0.0.1:5432/cleanapp
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DATABASE_PROVIDER: postgresql
      DATABASE_URL: postgresql://admin:example@db:5432/cleanapp
    env_file: .env
volumes:
  postgres_data: