// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const databaseName = (process.env.DATABASE_NAME ?? "POSTGRESQL_PRISMA")
  .trim()
  .toUpperCase();
const useMysql = databaseName === "MYSQL_PRISMA";

export default defineConfig({
  schema: useMysql ? "prisma/schema.mysql.prisma" : "prisma/schema.prisma",
  migrations: {
    path: useMysql ? "prisma/migrations-mysql" : "prisma/migrations",
    seed: "node prisma/seed-runner.mjs",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
